/*
 Navicat Premium Data Transfer

 Source Server         : serverDevAtta-ygakseIP
 Source Server Type    : MariaDB
 Source Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 Source Host           : 10.0.2.121:3306
 Source Schema         : sikrsamlegacy4

 Target Server Type    : MariaDB
 Target Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 File Encoding         : 65001

 Date: 16/12/2025 16:56:12
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for penilaian_medis_ranap
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_medis_ranap`;
CREATE TABLE `penilaian_medis_ranap` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) NOT NULL,
  `anamnesis` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `hubungan` varchar(100) NOT NULL,
  `keluhan_utama` varchar(2000) NOT NULL DEFAULT '',
  `rps` varchar(2000) NOT NULL,
  `rpd` varchar(1000) NOT NULL DEFAULT '',
  `rpk` varchar(1000) NOT NULL,
  `rpo` varchar(1000) NOT NULL,
  `alergi` varchar(100) NOT NULL DEFAULT '',
  `keadaan` enum('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') NOT NULL,
  `gcs` varchar(10) NOT NULL,
  `kesadaran` enum('Compos Mentis','Apatis','Somnolen','Sopor','Koma') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `spo` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `kepala` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `mata` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `gigi` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `tht` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `thoraks` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `jantung` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `paru` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `abdomen` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `genital` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ekstremitas` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `kulit` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ket_fisik` text NOT NULL,
  `ket_lokalis` text NOT NULL,
  `lab` text NOT NULL,
  `rad` text NOT NULL,
  `penunjang` text NOT NULL,
  `diagnosis` varchar(500) NOT NULL,
  `tata` text NOT NULL,
  `edukasi` varchar(1000) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `kd_dokter` (`kd_dokter`) USING BTREE,
  CONSTRAINT `penilaian_medis_ranap_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_medis_ranap_jantung
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_medis_ranap_jantung`;
CREATE TABLE `penilaian_medis_ranap_jantung` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) NOT NULL,
  `anamnesis` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `hubungan` varchar(30) NOT NULL,
  `keluhan_utama` varchar(2000) NOT NULL DEFAULT '',
  `rps` varchar(2000) NOT NULL,
  `rpk` varchar(1000) NOT NULL DEFAULT '',
  `rpd` varchar(1000) NOT NULL DEFAULT '',
  `rpo` varchar(1000) NOT NULL,
  `alergi` varchar(50) NOT NULL DEFAULT '',
  `td` varchar(8) NOT NULL DEFAULT '',
  `bb` varchar(5) NOT NULL,
  `tb` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL,
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL DEFAULT '',
  `keadaan_umum` enum('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') DEFAULT NULL,
  `nyeri` varchar(50) NOT NULL DEFAULT '',
  `status_nutrisi` varchar(50) NOT NULL DEFAULT '',
  `jantung` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_jantung` varchar(50) DEFAULT NULL,
  `paru` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_paru` varchar(50) DEFAULT NULL,
  `ekstrimitas` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_ekstrimitas` varchar(50) DEFAULT NULL,
  `lainnya` varchar(1000) NOT NULL,
  `lab` varchar(500) NOT NULL,
  `ekg` varchar(500) NOT NULL,
  `penunjang_lain` varchar(500) NOT NULL,
  `diagnosis` varchar(500) NOT NULL,
  `diagnosis2` varchar(500) NOT NULL,
  `permasalahan` varchar(500) NOT NULL,
  `terapi` varchar(500) NOT NULL,
  `tindakan` varchar(500) NOT NULL,
  `edukasi` varchar(500) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `kd_dokter` (`kd_dokter`) USING BTREE,
  CONSTRAINT `penilaian_medis_ranap_jantung_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_jantung_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_medis_ranap_kandungan
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_medis_ranap_kandungan`;
CREATE TABLE `penilaian_medis_ranap_kandungan` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) NOT NULL,
  `anamnesis` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `hubungan` varchar(100) NOT NULL,
  `keluhan_utama` varchar(2000) NOT NULL DEFAULT '',
  `rps` varchar(2000) NOT NULL,
  `rpd` varchar(1000) NOT NULL DEFAULT '',
  `rpk` varchar(1000) NOT NULL,
  `rpo` varchar(1000) NOT NULL,
  `alergi` varchar(100) NOT NULL DEFAULT '',
  `keadaan` enum('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') NOT NULL,
  `gcs` varchar(10) NOT NULL,
  `kesadaran` enum('Compos Mentis','Apatis','Somnolen','Sopor','Koma') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `spo` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `kepala` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `mata` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `gigi` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `tht` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `thoraks` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `jantung` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `paru` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `abdomen` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `genital` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ekstremitas` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `kulit` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ket_fisik` text NOT NULL,
  `tfu` varchar(10) NOT NULL,
  `tbj` varchar(10) NOT NULL,
  `his` varchar(10) NOT NULL,
  `kontraksi` enum('Ada','Tidak') NOT NULL,
  `djj` varchar(10) NOT NULL,
  `inspeksi` text NOT NULL,
  `inspekulo` text NOT NULL,
  `vt` text NOT NULL,
  `rt` text NOT NULL,
  `ultra` text NOT NULL,
  `kardio` text NOT NULL,
  `lab` text NOT NULL,
  `diagnosis` varchar(500) NOT NULL,
  `tata` text NOT NULL,
  `edukasi` varchar(1000) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `kd_dokter` (`kd_dokter`) USING BTREE,
  CONSTRAINT `penilaian_medis_ranap_kandungan_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_kandungan_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_medis_ranap_neonatus
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_medis_ranap_neonatus`;
CREATE TABLE `penilaian_medis_ranap_neonatus` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) NOT NULL,
  `no_rkm_medis_ibu` varchar(15) DEFAULT NULL,
  `g` varchar(10) DEFAULT NULL,
  `p` varchar(10) DEFAULT NULL,
  `a` varchar(10) DEFAULT NULL,
  `hidup` varchar(10) DEFAULT NULL,
  `usiahamil` varchar(10) DEFAULT NULL,
  `hbsag` enum('Negatif (-)','Positif (+)','Tidak Ada Keterangan') DEFAULT NULL,
  `hiv` enum('Negatif (-)','Positif (+)','Tidak Ada Keterangan') DEFAULT NULL,
  `syphilis` enum('Negatif (-)','Positif (+)','Tidak Ada Keterangan') DEFAULT NULL,
  `riwayat_obstetri_ibu` enum('Tidak Ada','Demam Pada Ibu > 38°C','Ketuban Pecah Dini','Ada Ketuban Berbau/Keruh','Nyeri Berkemih/ISK','Ibu DM','Ibu Hipertensi','Ibu Perdarahan','Ibu Eklamsia/Pre Eklamsia','Lainnya') DEFAULT NULL,
  `keterangan_riwayat_obstetri_ibu` varchar(70) DEFAULT NULL,
  `faktor_risiko_neonatal` enum('Tidak Ada','Kelahiran Preterm','Kelahiran Post Date','DJJ Abnormal','Lainnya') DEFAULT NULL,
  `keterangan_faktor_risiko_neonatal` varchar(70) DEFAULT NULL,
  `tanggal_persalinan` datetime NOT NULL,
  `bersalin_di` varchar(70) DEFAULT NULL,
  `inisiasi_menyusui` enum('Ya','Tidak') DEFAULT NULL,
  `jenis_persalinan` enum('Spontan/Normal','Induksi','Sectio Caesaria','Vacum Ekstraksi') DEFAULT NULL,
  `indikasi` varchar(70) DEFAULT NULL,
  `aterm` enum('Ya','Tidak') DEFAULT NULL,
  `bernafas` enum('Ya','Tidak') DEFAULT NULL,
  `tanus_otot` enum('Ya','Tidak') DEFAULT NULL,
  `cairan_amnion` enum('Ya','Tidak') DEFAULT NULL,
  `f1` varchar(1) NOT NULL,
  `u1` varchar(1) NOT NULL,
  `t1` varchar(1) NOT NULL,
  `r1` varchar(1) NOT NULL,
  `w1` varchar(1) NOT NULL,
  `n1` varchar(2) NOT NULL,
  `f5` varchar(1) NOT NULL,
  `u5` varchar(1) NOT NULL,
  `t5` varchar(1) NOT NULL,
  `r5` varchar(1) NOT NULL,
  `w5` varchar(1) NOT NULL,
  `n5` varchar(2) NOT NULL,
  `f10` varchar(1) NOT NULL,
  `u10` varchar(1) NOT NULL,
  `t10` varchar(1) NOT NULL,
  `r10` varchar(1) NOT NULL,
  `w10` varchar(1) NOT NULL,
  `n10` varchar(2) NOT NULL,
  `frekuensi_napas` enum('< 60','60 - 80','> 80') DEFAULT NULL,
  `nilai_frekuensi_napas` tinyint(4) DEFAULT NULL,
  `retraksi` enum('Tidak Ada','Retraksi Ringan','Retraksi Berat') DEFAULT NULL,
  `nilai_retraksi` tinyint(4) DEFAULT NULL,
  `sianosis` enum('Tidak Ada','Hilang Dengan O2','Tidak Hilang Dengan O2') DEFAULT NULL,
  `nilai_sianosis` tinyint(4) DEFAULT NULL,
  `jalan_masuk_udara` enum('Baik','Penurunan Ringan Udara Masuk','Tidak Ada Udara Masuk') DEFAULT NULL,
  `nilai_jalan_masuk_udara` tinyint(4) DEFAULT NULL,
  `grunting` enum('Tidak Ada','Dapat Didengar Dengan Stetoskop','Dapat Didengar Tanpa Stetoskop') DEFAULT NULL,
  `nilai_grunting` tinyint(4) DEFAULT NULL,
  `total_down_score` tinyint(4) DEFAULT NULL,
  `keterangan_down_Score` varchar(40) DEFAULT NULL,
  `nadi` varchar(5) DEFAULT NULL,
  `rr` varchar(5) DEFAULT NULL,
  `suhu` varchar(5) DEFAULT NULL,
  `saturasi` varchar(5) DEFAULT NULL,
  `bb` varchar(5) DEFAULT NULL,
  `pb` varchar(5) DEFAULT NULL,
  `lk` varchar(5) DEFAULT NULL,
  `ld` varchar(5) DEFAULT NULL,
  `keadaan_umum` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_keadaan_umum` varchar(50) DEFAULT NULL,
  `kulit` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_kulit` varchar(50) DEFAULT NULL,
  `kepala` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_kepala` varchar(50) DEFAULT NULL,
  `mata` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_mata` varchar(50) DEFAULT NULL,
  `telinga` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_telinga` varchar(50) DEFAULT NULL,
  `hidung` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_hidung` varchar(50) DEFAULT NULL,
  `mulut` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_mulut` varchar(50) DEFAULT NULL,
  `tenggorokan` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_tenggorokan` varchar(50) DEFAULT NULL,
  `leher` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_leher` varchar(50) DEFAULT NULL,
  `thorax` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_thorax` varchar(50) DEFAULT NULL,
  `abdomen` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_abdomen` varchar(50) DEFAULT NULL,
  `genitalia` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_genitalia` varchar(50) DEFAULT NULL,
  `anus` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_anus` varchar(50) DEFAULT NULL,
  `muskulos` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_muskulos` varchar(50) DEFAULT NULL,
  `ekstrimitas` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_ekstrimitas` varchar(50) DEFAULT NULL,
  `paru` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_paru` varchar(50) DEFAULT NULL,
  `refleks` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `keterangan_refleks` varchar(50) DEFAULT NULL,
  `kelainan_lainnya` varchar(80) DEFAULT NULL,
  `pemeriksaan_regional` varchar(500) NOT NULL,
  `lab` varchar(500) NOT NULL,
  `radiologi` varchar(500) NOT NULL,
  `penunjanglainnya` varchar(500) NOT NULL,
  `diagnosis` varchar(500) NOT NULL,
  `tata` varchar(2000) NOT NULL,
  `edukasi` varchar(1000) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `kd_dokter` (`kd_dokter`) USING BTREE,
  KEY `no_rkm_medis` (`no_rkm_medis_ibu`) USING BTREE,
  CONSTRAINT `penilaian_medis_ranap_neonatus_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_neonatus_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_neonatus_ibfk_3` FOREIGN KEY (`no_rkm_medis_ibu`) REFERENCES `pasien` (`no_rkm_medis`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_medis_ranap_psikiatrik
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_medis_ranap_psikiatrik`;
CREATE TABLE `penilaian_medis_ranap_psikiatrik` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) NOT NULL,
  `anamnesis` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `hubungan` varchar(30) NOT NULL,
  `keluhan_utama` varchar(2000) NOT NULL DEFAULT '',
  `rps` varchar(2000) NOT NULL,
  `rpd` varchar(1000) NOT NULL DEFAULT '',
  `rpk` varchar(1000) NOT NULL,
  `rpo` varchar(1000) NOT NULL,
  `alergi` varchar(50) NOT NULL,
  `penampilan` varchar(200) NOT NULL,
  `pembicaraan` varchar(200) NOT NULL,
  `psikomotor` varchar(200) NOT NULL,
  `sikap` varchar(200) NOT NULL,
  `mood` varchar(200) NOT NULL,
  `fungsi_kognitif` varchar(200) NOT NULL,
  `gangguan_persepsi` varchar(200) NOT NULL,
  `proses_pikir` varchar(200) NOT NULL,
  `pengendalian_impuls` varchar(200) NOT NULL,
  `tilikan` varchar(200) NOT NULL,
  `rta` varchar(200) NOT NULL,
  `skala_penilaian_khusus` varchar(200) NOT NULL,
  `keadaan` enum('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') NOT NULL,
  `gcs` varchar(10) NOT NULL,
  `kesadaran` enum('Compos Mentis','Apatis','Somnolen','Sopor','Koma') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `spo` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `kepala` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `gigi` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `tht` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `thoraks` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `abdomen` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `genital` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ekstremitas` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `kulit` enum('Normal','Abnormal','Tidak Diperiksa') NOT NULL,
  `ket_fisik` varchar(1000) NOT NULL,
  `penunjang` varchar(1000) NOT NULL,
  `diagnosis` varchar(300) NOT NULL,
  `tata` varchar(1000) NOT NULL,
  `konsulrujuk` varchar(500) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `kd_dokter` (`kd_dokter`) USING BTREE,
  CONSTRAINT `penilaian_medis_ranap_psikiatrik_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_ranap_psikiatrik_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
