/*
 Navicat Premium Data Transfer

 Source Server         : serverDevAtta-ygakseIP
 Source Server Type    : MariaDB
 Source Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 Source Host           : 10.0.2.121:3306
 Source Schema         : sikrsamlegacy5

 Target Server Type    : MariaDB
 Target Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 File Encoding         : 65001

 Date: 02/01/2026 11:34:46
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_gigi
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_gigi`;
CREATE TABLE `penilaian_awal_keperawatan_gigi` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `bmi` varchar(10) NOT NULL,
  `keluhan_utama` varchar(150) NOT NULL DEFAULT '',
  `riwayat_penyakit` enum('Tidak Ada','Diabetes Melitus','Hipertensi','Penyakit Jantung','HIV','Hepatitis','Haemophilia','Lain-lain') DEFAULT NULL,
  `ket_riwayat_penyakit` varchar(30) NOT NULL,
  `alergi` varchar(25) NOT NULL DEFAULT '',
  `riwayat_perawatan_gigi` enum('Tidak','Ya, Kapan') NOT NULL,
  `ket_riwayat_perawatan_gigi` varchar(50) NOT NULL DEFAULT '',
  `kebiasaan_sikat_gigi` enum('1x','2x','3x','Mandi','Setelah Makan','Sebelum Tidur') NOT NULL,
  `kebiasaan_lain` enum('Tidak ada','Minum kopi/teh','Minum alkohol','Bruxism','Menggigit pensil','Mengunyah 1 sisi rahang','Merokok','Lain-lain') DEFAULT NULL,
  `ket_kebiasaan_lain` varchar(30) NOT NULL,
  `obat_yang_diminum_saatini` varchar(100) DEFAULT NULL,
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_alat_bantu` varchar(30) NOT NULL,
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `status_psiko` enum('Tenang','Takut','Cemas','Depresi','Lain-lain') NOT NULL,
  `ket_psiko` varchar(70) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(40) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `frekuensi` varchar(25) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Medengar Musik','Minum Obat','Tidak ada nyeri','Lain-lain') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) NOT NULL,
  `kebersihan_mulut` enum('Baik','Cukup','Kurang') NOT NULL,
  `mukosa_mulut` enum('Normal','Pigmentasi','Radang') NOT NULL,
  `karies` enum('Ada','Tidak') NOT NULL,
  `karang_gigi` enum('Ada','Tidak') NOT NULL,
  `gingiva` enum('Normal','Radang') NOT NULL,
  `palatum` enum('Normal','Radang') NOT NULL,
  `rencana` varchar(200) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_gigi_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_gigi_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_igd
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_igd`;
CREATE TABLE `penilaian_awal_keperawatan_igd` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `keluhan_utama` text NOT NULL,
  `rpd` text NOT NULL,
  `rpo` text NOT NULL,
  `status_kehamilan` enum('Tidak Hamil','Hamil') NOT NULL,
  `gravida` varchar(20) DEFAULT NULL,
  `para` varchar(20) DEFAULT NULL,
  `abortus` varchar(20) DEFAULT NULL,
  `hpht` varchar(20) DEFAULT NULL,
  `tekanan` enum('TAK','Sakit Kepala','Muntah','Pusing','Bingung') NOT NULL,
  `pupil` enum('Normal','Miosis','Isokor','Anisokor') NOT NULL,
  `neurosensorik` enum('TAK','Spasme Otot','Perubahan Sensorik','Perubahan Motorik','Perubahan Bentuk Ekstremitas','Penurunan Tingkat Kesadaran','Fraktur/Dislokasi','Luksasio','Kerusakan Jaringan/Luka') NOT NULL,
  `integumen` enum('TAK','Luka Bakar','Luka Robek','Lecet','Luka Decubitus','Luka Gangren') NOT NULL,
  `turgor` enum('Baik','Menurun') NOT NULL,
  `edema` enum('Tidak Ada','Ekstremitas','Seluruh Tubuh','Asites','Palpebrae') NOT NULL,
  `mukosa` enum('Lembab','Kering') NOT NULL,
  `perdarahan` enum('Tidak Ada','Ada') NOT NULL,
  `jumlah_perdarahan` char(5) DEFAULT NULL,
  `warna_perdarahan` varchar(40) DEFAULT '',
  `intoksikasi` enum('Tidak Ada','Ada','Gigitan Binatang','Zat Kimia','Gas','Obat') NOT NULL,
  `bab` char(2) DEFAULT NULL,
  `xbab` varchar(10) DEFAULT NULL,
  `kbab` varchar(40) DEFAULT NULL,
  `wbab` varchar(40) DEFAULT NULL,
  `bak` char(2) DEFAULT NULL,
  `xbak` varchar(10) DEFAULT NULL,
  `wbak` varchar(40) DEFAULT '',
  `lbak` varchar(40) DEFAULT '',
  `psikologis` enum('Tidak Ada Masalah','Marah','Takut','Depresi','Cepat Lelah','Cemas','Gelisah','Lain-lain') NOT NULL,
  `jiwa` enum('Ya','Tidak') NOT NULL,
  `perilaku` enum('Perilaku Kekerasan','Gangguan Efek','Gangguan Memori','Halusinasi','Kecenderungan Percobaan Bunuh Diri','Lainnya','-') NOT NULL,
  `dilaporkan` varchar(50) DEFAULT NULL,
  `sebutkan` varchar(50) DEFAULT NULL,
  `hubungan` enum('Harmonis','Kurang Harmonis','Tidak Harmonis','Konflik Besar') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(50) DEFAULT '',
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `pendidikan_pj` enum('-','TS','TK','SD','SMP','SMA','SLTA/SEDERAJAT','D1','D2','D3','D4','S1','S2','S3') NOT NULL,
  `ket_pendidikan_pj` varchar(50) DEFAULT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `kemampuan` enum('Mandiri','Bantuan Minimal','Bantuan Sebagian','Ketergantungan Total') NOT NULL,
  `aktifitas` enum('Tirah Baring','Duduk','Berjalan') NOT NULL,
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) DEFAULT '',
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-lain') NOT NULL,
  `ket_quality` varchar(50) NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Medengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) DEFAULT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) DEFAULT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) DEFAULT NULL,
  `rencana` text NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_igd_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_igd_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_kebidanan
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_kebidanan`;
CREATE TABLE `penilaian_awal_keperawatan_kebidanan` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(10) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `lila` varchar(5) NOT NULL,
  `bmi` varchar(10) NOT NULL,
  `tfu` varchar(10) NOT NULL,
  `tbj` varchar(10) NOT NULL,
  `letak` varchar(10) NOT NULL,
  `presentasi` varchar(10) NOT NULL,
  `penurunan` varchar(10) NOT NULL,
  `his` varchar(10) NOT NULL,
  `kekuatan` varchar(10) NOT NULL,
  `lamanya` varchar(10) NOT NULL,
  `bjj` varchar(10) NOT NULL,
  `ket_bjj` enum('Teratur','Tidak Teratur') NOT NULL,
  `portio` varchar(10) NOT NULL,
  `serviks` varchar(10) NOT NULL,
  `ketuban` varchar(10) NOT NULL,
  `hodge` varchar(10) NOT NULL,
  `inspekulo` enum('Dilakukan','Tidak') NOT NULL,
  `ket_inspekulo` varchar(50) NOT NULL,
  `ctg` enum('Dilakukan','Tidak') NOT NULL,
  `ket_ctg` varchar(50) NOT NULL,
  `usg` enum('Dilakukan','Tidak') NOT NULL,
  `ket_usg` varchar(50) NOT NULL,
  `lab` enum('Dilakukan','Tidak') NOT NULL,
  `ket_lab` varchar(50) NOT NULL,
  `lakmus` enum('Dilakukan','Tidak') NOT NULL,
  `ket_lakmus` varchar(50) NOT NULL,
  `panggul` enum('Luas','Sedang','Sempit','Tidak Dilakukan Pemeriksaan') NOT NULL,
  `keluhan_utama` varchar(1000) NOT NULL DEFAULT '',
  `umur` varchar(10) NOT NULL,
  `lama` varchar(10) NOT NULL,
  `banyaknya` varchar(10) NOT NULL,
  `haid` varchar(20) NOT NULL,
  `siklus` varchar(10) NOT NULL,
  `ket_siklus` enum('Teratur','Tidak Teratur') NOT NULL,
  `ket_siklus1` enum('Tidak Ada Masalah','Dismenorhea','Spotting','Menorhagia','PMS') NOT NULL,
  `status` enum('Menikah','Tidak / Belum Menikah') NOT NULL,
  `kali` varchar(5) NOT NULL,
  `usia1` varchar(5) NOT NULL,
  `ket1` enum('-','Masih Menikah','Cerai','Meninggal') NOT NULL,
  `usia2` varchar(5) DEFAULT NULL,
  `ket2` enum('-','Masih Menikah','Cerai','Meninggal') DEFAULT NULL,
  `usia3` varchar(5) DEFAULT NULL,
  `ket3` enum('-','Masih Menikah','Cerai','Meninggal') DEFAULT NULL,
  `hpht` date DEFAULT NULL,
  `usia_kehamilan` varchar(10) NOT NULL,
  `tp` date DEFAULT NULL,
  `imunisasi` enum('Tidak','Ya') NOT NULL,
  `ket_imunisasi` varchar(10) NOT NULL,
  `g` varchar(10) NOT NULL,
  `p` varchar(10) NOT NULL,
  `a` varchar(10) NOT NULL,
  `hidup` varchar(10) NOT NULL,
  `ginekologi` enum('Tidak Ada','Infertilitas','Infeksi Virus','PMS','Cervisitis Kronis','Endometriosis','Mioma','Polip Cervix','Kanker Kandungan','Operasi Kandungan') NOT NULL,
  `kebiasaan` enum('-','Obat Obatan','Vitamin','Jamu Jamuan') NOT NULL,
  `ket_kebiasaan` varchar(50) NOT NULL,
  `kebiasaan1` enum('Tidak','Ya') NOT NULL,
  `ket_kebiasaan1` varchar(5) NOT NULL,
  `kebiasaan2` enum('Tidak','Ya') NOT NULL,
  `ket_kebiasaan2` varchar(5) NOT NULL,
  `kebiasaan3` enum('Tidak','Ya') NOT NULL,
  `kb` enum('Belum Pernah','Suntik','Pil','AKDR','MOW','Implan','Kondom','Kalender','MAL','Coitus Interuptus') NOT NULL,
  `ket_kb` varchar(10) NOT NULL,
  `komplikasi` enum('Tidak Ada','Ada') NOT NULL,
  `ket_komplikasi` varchar(50) NOT NULL,
  `berhenti` varchar(20) NOT NULL,
  `alasan` varchar(50) NOT NULL,
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) NOT NULL DEFAULT '',
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `adl` enum('Mandiri','Dibantu') NOT NULL,
  `status_psiko` enum('Tenang','Takut','Cemas','Depresi','Lain-Lain') NOT NULL,
  `ket_psiko` varchar(50) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(50) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak Beresiko (Tidak Ditemukan A Dan B)','Resiko Rendah (Ditemukan A/B)','Resiko Tinggi (Ditemukan A Dan B)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(10) NOT NULL,
  `sg1` enum('Ya','Tidak','Tidak Yakin','Ya, 1-5 Kg','Ya, 6-10 Kg','Ya, 11-15 Kg','Ya, >15 Kg') NOT NULL,
  `nilai1` enum('0','1','2','3','4') NOT NULL,
  `sg2` enum('Ya','Tidak') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `total_hasil` varchar(5) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-Lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-Lain') NOT NULL,
  `ket_quality` varchar(40) NOT NULL,
  `lokasi` varchar(40) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(5) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Mendengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(10) NOT NULL,
  `masalah` varchar(1000) NOT NULL,
  `tindakan` varchar(1000) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_kebidanan_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_kebidanan_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_mata
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_mata`;
CREATE TABLE `penilaian_awal_keperawatan_mata` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `bmi` varchar(10) NOT NULL,
  `keluhan_utama` varchar(150) NOT NULL DEFAULT '',
  `rpd` varchar(100) NOT NULL DEFAULT '',
  `rps` varchar(100) NOT NULL DEFAULT '',
  `rpk` varchar(100) NOT NULL,
  `rpo` varchar(100) NOT NULL,
  `alergi` varchar(25) NOT NULL DEFAULT '',
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) NOT NULL DEFAULT '',
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `adl` enum('Mandiri','Dibantu') NOT NULL,
  `status_psiko` enum('Tenang','Takut','Cemas','Depresi','Lain-lain') NOT NULL,
  `ket_psiko` varchar(70) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(40) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) NOT NULL,
  `sg1` enum('Tidak','Tidak Yakin','Ya, 1-5 Kg','Ya, 6-10 Kg','Ya, 11-15 Kg','Ya, >15 Kg') NOT NULL,
  `nilai1` enum('0','1','2','3','4') NOT NULL,
  `sg2` enum('Ya','Tidak') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `sg3` enum('Ya','Tidak') NOT NULL,
  `nilai3` enum('0','1') NOT NULL,
  `sg4` enum('Ya','Tidak') NOT NULL,
  `nilai4` enum('0','1') NOT NULL,
  `total_hasil` tinyint(4) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-lain') NOT NULL,
  `ket_quality` varchar(50) NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Medengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) NOT NULL,
  `visuskanan` varchar(20) NOT NULL,
  `visuskiri` varchar(20) NOT NULL,
  `refraksikanan` varchar(20) NOT NULL,
  `refraksikiri` varchar(20) NOT NULL,
  `tiokanan` varchar(20) NOT NULL,
  `tiokiri` varchar(20) NOT NULL,
  `palberakanan` varchar(20) NOT NULL,
  `palberakiri` varchar(20) NOT NULL,
  `konjungtivakanan` varchar(20) NOT NULL,
  `konjungtivakiri` varchar(20) NOT NULL,
  `sklerakanan` varchar(20) NOT NULL,
  `sklerakiri` varchar(20) NOT NULL,
  `korneakanan` varchar(20) NOT NULL,
  `korneakiri` varchar(20) NOT NULL,
  `bmdkanan` varchar(20) NOT NULL,
  `bmdkiri` varchar(20) NOT NULL,
  `iriskanan` varchar(20) NOT NULL,
  `iriskiri` varchar(20) NOT NULL,
  `pupilkanan` varchar(20) NOT NULL,
  `pupilkiri` varchar(20) NOT NULL,
  `lensakanan` varchar(20) NOT NULL,
  `lensakiri` varchar(20) NOT NULL,
  `oftalmoskopikanan` varchar(100) NOT NULL,
  `oftalmoskopikiri` varchar(100) NOT NULL,
  `rencana` varchar(100) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_mata_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_mata_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=COMPACT;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_ralan
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_ralan`;
CREATE TABLE `penilaian_awal_keperawatan_ralan` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `bmi` varchar(10) NOT NULL,
  `keluhan_utama` varchar(150) NOT NULL DEFAULT '',
  `rpd` varchar(100) NOT NULL DEFAULT '',
  `rpk` varchar(100) NOT NULL,
  `rpo` varchar(100) NOT NULL,
  `alergi` varchar(25) NOT NULL DEFAULT '',
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) NOT NULL DEFAULT '',
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `adl` enum('Mandiri','Dibantu') NOT NULL,
  `status_psiko` enum('Tenang','Takut','Cemas','Depresi','Lain-lain') NOT NULL,
  `ket_psiko` varchar(70) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(40) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) NOT NULL,
  `sg1` enum('Tidak','Tidak Yakin','Ya, 1-5 Kg','Ya, 6-10 Kg','Ya, 11-15 Kg','Ya, >15 Kg') NOT NULL,
  `nilai1` enum('0','1','2','3','4') NOT NULL,
  `sg2` enum('Ya','Tidak') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `total_hasil` tinyint(4) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-lain') NOT NULL,
  `ket_quality` varchar(50) NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Medengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) NOT NULL,
  `rencana` varchar(200) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_ralan_bayi
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_ralan_bayi`;
CREATE TABLE `penilaian_awal_keperawatan_ralan_bayi` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(5) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `lp` varchar(5) NOT NULL DEFAULT '',
  `lk` varchar(5) NOT NULL DEFAULT '',
  `ld` varchar(5) NOT NULL DEFAULT '',
  `keluhan_utama` varchar(150) NOT NULL DEFAULT '',
  `rpd` varchar(100) NOT NULL DEFAULT '',
  `rpk` varchar(100) NOT NULL,
  `rpo` varchar(100) NOT NULL,
  `alergi` varchar(25) NOT NULL DEFAULT '',
  `anakke` varchar(4) NOT NULL,
  `darisaudara` varchar(4) NOT NULL,
  `caralahir` enum('Spontan','Sectio Caesaria','Lain-Lain') NOT NULL,
  `ket_caralahir` varchar(30) NOT NULL,
  `umurkelahiran` enum('Cukup Bulan','Kurang Bulan') NOT NULL,
  `kelainanbawaan` enum('Tidak Ada','Ada') NOT NULL,
  `ket_kelainan_bawaan` varchar(30) NOT NULL,
  `usiatengkurap` varchar(15) NOT NULL,
  `usiaduduk` varchar(15) NOT NULL,
  `usiaberdiri` varchar(15) NOT NULL,
  `usiagigipertama` varchar(15) NOT NULL,
  `usiaberjalan` varchar(15) NOT NULL,
  `usiabicara` varchar(15) NOT NULL,
  `usiamembaca` varchar(15) NOT NULL,
  `usiamenulis` varchar(15) NOT NULL,
  `gangguanemosi` varchar(50) NOT NULL,
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) NOT NULL DEFAULT '',
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `adl` enum('Mandiri','Dibantu') NOT NULL,
  `status_psiko` enum('Tenang','Takut','Tempertantrum','Cemas','Depresi','Lain-lain') NOT NULL,
  `ket_psiko` varchar(70) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `pengasuh` enum('Orang Tua','Kakek/Nenek','Keluarga Lainnya') NOT NULL,
  `ket_pengasuh` varchar(40) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Orang Tua','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) NOT NULL,
  `sg1` enum('Tidak','Ya') NOT NULL,
  `nilai1` enum('0','1') NOT NULL,
  `sg2` enum('Tidak','Ya') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `sg3` enum('Tidak','Ya') NOT NULL,
  `nilai3` enum('0','1') NOT NULL,
  `sg4` enum('Tidak','Ya') NOT NULL,
  `nilai4` enum('0','1') NOT NULL,
  `total_hasil` tinyint(4) NOT NULL,
  `wajah` enum('Tersenyum/tidak ada ekspresi khusus','Terkadang meringis/menarik diri','Sering menggetarkan dagu dan mengatupkan rahang') NOT NULL,
  `nilaiwajah` enum('0','1','2') NOT NULL,
  `kaki` enum('Gerakan normal/relaksasi','Tidak tenang/tegang','Kaki dibuat menendang/menarik') NOT NULL,
  `nilaikaki` enum('0','1','2') NOT NULL,
  `aktifitas` enum('Tidur posisi normal, mudah bergerak','Gerakan menggeliat/berguling, kaku','Melengkungkan punggung/kaku menghentak') NOT NULL,
  `nilaiaktifitas` enum('0','1','2') NOT NULL,
  `menangis` enum('Tidak menangis (mudah bergerak)','Mengerang/merengek','Menangis terus menerus, terisak, menjerit') NOT NULL,
  `nilaimenangis` enum('0','1','2') NOT NULL,
  `bersuara` enum('Bersuara normal/tenang','Tenang bila dipeluk, digendong/diajak bicara','Sulit untuk menenangkan') NOT NULL,
  `nilaibersuara` enum('0','1','2') NOT NULL,
  `hasilnyeri` tinyint(4) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `frekuensi` varchar(25) NOT NULL,
  `nyeri_hilang` enum('Minum Obat','Istirahat','Mendengar Music','Berubah Posisi/Tidur','Lain-lain') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) NOT NULL,
  `rencana` varchar(200) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_bayi_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_bayi_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_ralan_psikiatri
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_ralan_psikiatri`;
CREATE TABLE `penilaian_awal_keperawatan_ralan_psikiatri` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `keluhan_utama` varchar(500) NOT NULL DEFAULT '',
  `rkd_sakit_sejak` varchar(8) NOT NULL,
  `rkd_keluhan` varchar(500) NOT NULL,
  `rkd_berobat` enum('Tidak','Ya, Alternatif','Ya, RS','Ya, Puskesmas') NOT NULL,
  `rkd_hasil_pengobatan` enum('Berhasil','Tidak Berhasil') NOT NULL,
  `fp_putus_obat` enum('Tidak','Ya') NOT NULL,
  `ket_putus_obat` varchar(50) NOT NULL,
  `fp_ekonomi` enum('Tidak','Ya') NOT NULL,
  `ket_masalah_ekonomi` varchar(50) NOT NULL,
  `fp_masalah_fisik` enum('Tidak','Ya') NOT NULL,
  `ket_masalah_fisik` varchar(50) NOT NULL,
  `fp_masalah_psikososial` enum('Tidak','Ya') NOT NULL,
  `ket_masalah_psikososial` varchar(50) NOT NULL,
  `rh_keluarga` enum('Tidak','Ya') NOT NULL,
  `ket_rh_keluarga` varchar(50) NOT NULL,
  `resiko_bunuh_diri` enum('Tidak','Ya') NOT NULL,
  `rbd_ide` enum('Tidak','Ya') NOT NULL,
  `ket_rbd_ide` varchar(50) NOT NULL,
  `rbd_rencana` enum('Tidak','Ya') NOT NULL,
  `ket_rbd_rencana` varchar(50) NOT NULL,
  `rbd_alat` enum('Tidak','Ya') NOT NULL,
  `ket_rbd_alat` varchar(50) NOT NULL,
  `rbd_percobaan` enum('Tidak','Ya') NOT NULL,
  `ket_rbd_percobaan` varchar(15) NOT NULL,
  `rbd_keinginan` enum('Tidak','Ya') NOT NULL,
  `ket_rbd_keinginan` varchar(100) NOT NULL,
  `rpo_penggunaan` enum('Tidak','Ya') NOT NULL,
  `ket_rpo_penggunaan` varchar(20) NOT NULL,
  `rpo_efek_samping` enum('Tidak','Ya') NOT NULL,
  `ket_rpo_efek_samping` varchar(20) NOT NULL,
  `rpo_napza` enum('Tidak','Ya') NOT NULL,
  `ket_rpo_napza` varchar(25) NOT NULL,
  `ket_lama_pemakaian` varchar(8) NOT NULL,
  `ket_cara_pemakaian` varchar(15) NOT NULL,
  `ket_latar_belakang_pemakaian` varchar(60) NOT NULL,
  `rpo_penggunaan_obat_lainnya` enum('Tidak','Ya') NOT NULL,
  `ket_penggunaan_obat_lainnya` varchar(20) NOT NULL,
  `ket_alasan_penggunaan` varchar(65) NOT NULL,
  `rpo_alergi_obat` enum('Tidak','Ya') NOT NULL,
  `ket_alergi_obat` varchar(25) NOT NULL,
  `rpo_merokok` enum('Tidak','Ya') NOT NULL,
  `ket_merokok` varchar(25) NOT NULL,
  `rpo_minum_kopi` enum('Tidak','Ya') NOT NULL,
  `ket_minum_kopi` varchar(25) NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(5) NOT NULL,
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `pf_keluhan_fisik` enum('Tidak','Ya') NOT NULL,
  `ket_keluhan_fisik` varchar(100) NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(25) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-lain') NOT NULL,
  `ket_quality` varchar(50) NOT NULL,
  `lokasi` varchar(50) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(15) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Medengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `bmi` varchar(5) NOT NULL,
  `lapor_status_nutrisi` enum('Ya','Tidak') NOT NULL,
  `ket_lapor_status_nutrisi` varchar(15) NOT NULL,
  `sg1` enum('Tidak','Tidak Yakin','Ya, 1-5 Kg','Ya, 6-10 Kg','Ya, 11-15 Kg','Ya, >15 Kg') NOT NULL,
  `nilai1` enum('0','1','2','3','4') NOT NULL,
  `sg2` enum('Ya','Tidak') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `total_hasil` tinyint(4) NOT NULL,
  `resikojatuh` enum('Ya','Tidak') NOT NULL,
  `bjm` enum('Ya','Tidak') NOT NULL,
  `msa` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak beresiko (tidak ditemukan a dan b)','Resiko rendah (ditemukan a/b)','Resiko tinggi (ditemukan a dan b)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(15) NOT NULL,
  `adl_mandi` enum('Mandiri','Bantuan Minimal','Bantuan Total') NOT NULL,
  `adl_berpakaian` enum('Mandiri','Bantuan Minimal','Bantuan Total') NOT NULL,
  `adl_makan` enum('Mandiri','Bantuan Minimal','Bantuan Total') NOT NULL,
  `adl_bak` enum('Mandiri','Bantuan Minimal','Bantuan Total') NOT NULL,
  `adl_bab` enum('Mandiri','Bantuan Minimal','Bantuan Total') NOT NULL,
  `adl_hobi` enum('Ya','Tidak') NOT NULL,
  `ket_adl_hobi` varchar(50) NOT NULL,
  `adl_sosialisasi` enum('Ya','Tidak') NOT NULL,
  `ket_adl_sosialisasi` varchar(50) NOT NULL,
  `adl_kegiatan` enum('Ya','Tidak') NOT NULL,
  `ket_adl_kegiatan` varchar(50) NOT NULL,
  `sk_penampilan` enum('Bersih','Rapi','Tidak Rapi','Kotor','Tidak Seperti Biasanya','Pakaian Tidak Sesuai') NOT NULL,
  `sk_alam_perasaan` enum('Sesuai','Marah','Putus Asa','Tertekan','Sedih','Labil','Malu','Khawatir','Gembira Berlebihan','Merasa Tidak Mampu','Ketakutan','Tidak Berguna') NOT NULL,
  `sk_pembicaraan` enum('Sesuai','Cepat','Lambat','Membisu','Mendominasi','Mengancam','Inkoheren','Apatis','Keras','Gagap','Tidak Mampu Memulai Pembicaraan') NOT NULL,
  `sk_afek` enum('Sesuai','Datar','Tumpul','Labil','Tidak Sesuai') NOT NULL,
  `sk_aktifitas_motorik` enum('Normal','Tegang','Gelisah','Lesuh','Grimasem','TIK','Tremor','Agitasi','Konfulsif','Melamun','Sulit Diarahkan') NOT NULL,
  `sk_gangguan_ringan` enum('Gangguan Ringan','Gangguan Bermakna') NOT NULL,
  `sk_proses_pikir` enum('Sesuai','Sirkumsial','Kehilangan Asosiasi','Flight Of Ideas','Bloking','Pengulangan Pembicaraan','Tangensial') NOT NULL,
  `sk_orientasi` enum('Tidak','Ya') NOT NULL,
  `sk_tingkat_kesadaran_orientasi` enum('-','Bingung','Sedasi','Waktu','Stupor','Tempat','Orang') NOT NULL,
  `sk_memori` enum('Ganguan Daya Ingat Jangka Pendek','Ganguan Daya Ingat Jangka Panjang','Ganguan Daya Ingat Saat Ini','Konfabulasi') NOT NULL,
  `sk_interaksi` enum('Kooperatif','Tidak Kooperatif','Bermusuhan','Mudah Tersinggung','Curiga','Defensif','Kontak Mata Kurang') NOT NULL,
  `sk_konsentrasi` enum('Konsentrasi Baik','Mudah Beralih','Tidak Mampu Berkonsentrasi','Tidak Mampu Berhitung Sederhana') NOT NULL,
  `sk_persepsi` enum('Halusinasi','Pendengaran','Penghidung','Penglihatan','Pengecapan','Perabaan') NOT NULL,
  `ket_sk_persepsi` varchar(70) NOT NULL DEFAULT '',
  `sk_isi_pikir` enum('Sesuai','Obsesi','Fobia','Hipokondria','Depersonalisasi','Pikiran Magis','Ide Yang Terkait','Waham') NOT NULL,
  `sk_waham` enum('Kebesaran','Curiga','Agama','Nihilistik') NOT NULL,
  `ket_sk_waham` varchar(100) NOT NULL DEFAULT '',
  `sk_daya_tilik_diri` enum('Mengingkari Penyakit Yang Diderita','Menyalahkan Hal-hal Diluar Dirinya') NOT NULL,
  `ket_sk_daya_tilik_diri` varchar(100) NOT NULL DEFAULT '',
  `kk_pembelajaran` enum('Tidak','Ya') NOT NULL,
  `ket_kk_pembelajaran` enum('-','Pendengaran','Penglihatan','Kognitif','Fisik','Budaya','Emosi','Bahasa','Lainnya') NOT NULL,
  `ket_kk_pembelajaran_lainnya` varchar(50) NOT NULL DEFAULT '',
  `kk_Penerjamah` enum('Tidak','Ya') NOT NULL,
  `ket_kk_penerjamah_Lainnya` varchar(50) NOT NULL,
  `kk_bahasa_isyarat` enum('Tidak','Ya') NOT NULL,
  `kk_kebutuhan_edukasi` enum('Diagnosa Dan Manajemen Penyakit','Obat-obatan/Terapi','Diet Dan Nutrisi','Tindakan Keperawatan','Rehabilitasi','Manajemen Nyeri','Lain-lain') NOT NULL,
  `ket_kk_kebutuhan_edukasi` varchar(50) NOT NULL DEFAULT '',
  `rencana` varchar(200) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_psikiatri_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_ralan_psikiatri_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
