/*
 Navicat Premium Data Transfer

 Source Server         : produ
 Source Server Type    : MySQL
 Source Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 Source Host           : 10.0.2.5:3306
 Source Schema         : sikrs4m2106

 Target Server Type    : MySQL
 Target Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 File Encoding         : 65001

 Date: 10/09/2025 08:42:51
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for penilaian_awal_keperawatan_kebidanan
-- ----------------------------
DROP TABLE IF EXISTS `penilaian_awal_keperawatan_kebidanan`;
CREATE TABLE `penilaian_awal_keperawatan_kebidanan` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `informasi` enum('Autoanamnesis','Alloanamnesis') NOT NULL,
  `td` varchar(8) NOT NULL DEFAULT '',
  `nadi` varchar(5) NOT NULL DEFAULT '',
  `rr` varchar(5) NOT NULL,
  `suhu` varchar(5) NOT NULL DEFAULT '',
  `gcs` varchar(10) NOT NULL,
  `bb` varchar(5) NOT NULL DEFAULT '',
  `tb` varchar(5) NOT NULL DEFAULT '',
  `lila` varchar(5) NOT NULL,
  `bmi` varchar(10) NOT NULL,
  `tfu` varchar(10) NOT NULL,
  `tbj` varchar(10) NOT NULL,
  `letak` varchar(10) NOT NULL,
  `presentasi` varchar(10) NOT NULL,
  `penurunan` varchar(10) NOT NULL,
  `his` varchar(10) NOT NULL,
  `kekuatan` varchar(10) NOT NULL,
  `lamanya` varchar(10) NOT NULL,
  `bjj` varchar(10) NOT NULL,
  `ket_bjj` enum('Teratur','Tidak Teratur') NOT NULL,
  `portio` varchar(10) NOT NULL,
  `serviks` varchar(10) NOT NULL,
  `ketuban` varchar(10) NOT NULL,
  `hodge` varchar(10) NOT NULL,
  `inspekulo` enum('Dilakukan','Tidak') NOT NULL,
  `ket_inspekulo` varchar(50) NOT NULL,
  `ctg` enum('Dilakukan','Tidak') NOT NULL,
  `ket_ctg` varchar(50) NOT NULL,
  `usg` enum('Dilakukan','Tidak') NOT NULL,
  `ket_usg` varchar(50) NOT NULL,
  `lab` enum('Dilakukan','Tidak') NOT NULL,
  `ket_lab` varchar(50) NOT NULL,
  `lakmus` enum('Dilakukan','Tidak') NOT NULL,
  `ket_lakmus` varchar(50) NOT NULL,
  `panggul` enum('Luas','Sedang','Sempit','Tidak Dilakukan Pemeriksaan') NOT NULL,
  `keluhan_utama` varchar(1000) NOT NULL DEFAULT '',
  `umur` varchar(10) NOT NULL,
  `lama` varchar(10) NOT NULL,
  `banyaknya` varchar(10) NOT NULL,
  `haid` varchar(20) NOT NULL,
  `siklus` varchar(10) NOT NULL,
  `ket_siklus` enum('Teratur','Tidak Teratur') NOT NULL,
  `ket_siklus1` enum('Tidak Ada Masalah','Dismenorhea','Spotting','Menorhagia','PMS') NOT NULL,
  `status` enum('Menikah','Tidak / Belum Menikah') NOT NULL,
  `kali` varchar(5) NOT NULL,
  `usia1` varchar(5) NOT NULL,
  `ket1` enum('-','Masih Menikah','Cerai','Meninggal') NOT NULL,
  `usia2` varchar(5) DEFAULT NULL,
  `ket2` enum('-','Masih Menikah','Cerai','Meninggal') DEFAULT NULL,
  `usia3` varchar(5) DEFAULT NULL,
  `ket3` enum('-','Masih Menikah','Cerai','Meninggal') DEFAULT NULL,
  `hpht` date DEFAULT NULL,
  `usia_kehamilan` varchar(10) NOT NULL,
  `tp` date DEFAULT NULL,
  `imunisasi` enum('Tidak','Ya') NOT NULL,
  `ket_imunisasi` varchar(10) NOT NULL,
  `g` varchar(10) NOT NULL,
  `p` varchar(10) NOT NULL,
  `a` varchar(10) NOT NULL,
  `hidup` varchar(10) NOT NULL,
  `ginekologi` enum('Tidak Ada','Infertilitas','Infeksi Virus','PMS','Cervisitis Kronis','Endometriosis','Mioma','Polip Cervix','Kanker Kandungan','Operasi Kandungan') NOT NULL,
  `kebiasaan` enum('-','Obat Obatan','Vitamin','Jamu Jamuan') NOT NULL,
  `ket_kebiasaan` varchar(50) NOT NULL,
  `kebiasaan1` enum('Tidak','Ya') NOT NULL,
  `ket_kebiasaan1` varchar(5) NOT NULL,
  `kebiasaan2` enum('Tidak','Ya') NOT NULL,
  `ket_kebiasaan2` varchar(5) NOT NULL,
  `kebiasaan3` enum('Tidak','Ya') NOT NULL,
  `kb` enum('Belum Pernah','Suntik','Pil','AKDR','MOW','Implan','Kondom','Kalender','MAL','Coitus Interuptus') NOT NULL,
  `ket_kb` varchar(10) NOT NULL,
  `komplikasi` enum('Tidak Ada','Ada') NOT NULL,
  `ket_komplikasi` varchar(50) NOT NULL,
  `berhenti` varchar(20) NOT NULL,
  `alasan` varchar(50) NOT NULL,
  `alat_bantu` enum('Tidak','Ya') NOT NULL,
  `ket_bantu` varchar(50) NOT NULL DEFAULT '',
  `prothesa` enum('Tidak','Ya') NOT NULL,
  `ket_pro` varchar(50) NOT NULL,
  `adl` enum('Mandiri','Dibantu') NOT NULL,
  `status_psiko` enum('Tenang','Takut','Cemas','Depresi','Lain-Lain') NOT NULL,
  `ket_psiko` varchar(50) NOT NULL,
  `hub_keluarga` enum('Baik','Tidak Baik') NOT NULL,
  `tinggal_dengan` enum('Sendiri','Orang Tua','Suami / Istri','Lainnya') NOT NULL,
  `ket_tinggal` varchar(50) NOT NULL,
  `ekonomi` enum('Baik','Cukup','Kurang') NOT NULL,
  `budaya` enum('Tidak Ada','Ada') NOT NULL,
  `ket_budaya` varchar(50) NOT NULL,
  `edukasi` enum('Pasien','Keluarga') NOT NULL,
  `ket_edukasi` varchar(50) NOT NULL,
  `berjalan_a` enum('Ya','Tidak') NOT NULL,
  `berjalan_b` enum('Ya','Tidak') NOT NULL,
  `berjalan_c` enum('Ya','Tidak') NOT NULL,
  `hasil` enum('Tidak Beresiko (Tidak Ditemukan A Dan B)','Resiko Rendah (Ditemukan A/B)','Resiko Tinggi (Ditemukan A Dan B)') NOT NULL,
  `lapor` enum('Ya','Tidak') NOT NULL,
  `ket_lapor` varchar(10) NOT NULL,
  `sg1` enum('Tidak','Tidak Yakin','Ya(1-5 Kg)','Ya(6-10Kg)','Ya(11-15Kg)','Ya(>15Kg)') NOT NULL,
  `nilai1` enum('0','1','2','3','4') NOT NULL,
  `sg2` enum('Ya','Tidak') NOT NULL,
  `nilai2` enum('0','1') NOT NULL,
  `total_hasil` varchar(5) NOT NULL,
  `nyeri` enum('Tidak Ada Nyeri','Nyeri Akut','Nyeri Kronis') NOT NULL,
  `provokes` enum('Proses Penyakit','Benturan','Lain-Lain') NOT NULL,
  `ket_provokes` varchar(40) NOT NULL,
  `quality` enum('Seperti Tertusuk','Berdenyut','Teriris','Tertindih','Tertiban','Lain-Lain') NOT NULL,
  `ket_quality` varchar(40) NOT NULL,
  `lokasi` varchar(40) NOT NULL,
  `menyebar` enum('Tidak','Ya') NOT NULL,
  `skala_nyeri` enum('0','1','2','3','4','5','6','7','8','9','10') NOT NULL,
  `durasi` varchar(5) NOT NULL,
  `nyeri_hilang` enum('Istirahat','Mendengar Musik','Minum Obat') NOT NULL,
  `ket_nyeri` varchar(40) NOT NULL,
  `pada_dokter` enum('Tidak','Ya') NOT NULL,
  `ket_dokter` varchar(10) NOT NULL,
  `masalah` varchar(1000) NOT NULL,
  `tindakan` varchar(1000) NOT NULL,
  `nip` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  KEY `nip` (`nip`) USING BTREE,
  CONSTRAINT `penilaian_awal_keperawatan_kebidanan_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_awal_keperawatan_kebidanan_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
