/*
 Navicat Premium Data Transfer

 Source Server         : produ
 Source Server Type    : MySQL
 Source Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 Source Host           : 10.0.2.5:3306
 Source Schema         : sikrs4m2106

 Target Server Type    : MySQL
 Target Server Version : 100339 (10.3.39-MariaDB-0ubuntu0.20.04.2)
 File Encoding         : 65001

 Date: 30/11/2025 10:59:40
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for satu_sehat_mapping_radiologi
-- ----------------------------
DROP TABLE IF EXISTS `satu_sehat_mapping_radiologi`;
CREATE TABLE `satu_sehat_mapping_radiologi` (
  `kd_jenis_prw` varchar(15) NOT NULL,
  `code` varchar(15) DEFAULT NULL,
  `system` varchar(100) NOT NULL,
  `display` varchar(80) DEFAULT NULL,
  `sampel_code` varchar(15) NOT NULL,
  `sampel_system` varchar(100) NOT NULL,
  `sampel_display` varchar(80) NOT NULL,
  PRIMARY KEY (`kd_jenis_prw`),
  CONSTRAINT `satu_sehat_mapping_radiologi_ibfk_1` FOREIGN KEY (`kd_jenis_prw`) REFERENCES `jns_perawatan_radiologi` (`kd_jenis_prw`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of satu_sehat_mapping_radiologi
-- ----------------------------
BEGIN;
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000001', '24917-7', 'http://loinc.org', 'XR Skull Single view', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000002', '37867-9', 'http://loinc.org', 'XR Skull 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000003', '37858-8', 'http://loinc.org', 'XR Sinuses Lateral', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000004', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000005', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000006', '47983-2', 'http://loinc.org', 'XR Mastoid - bilateral 1 or 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000007', '24940-9', 'http://loinc.org', 'XR Cervical spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000008', '43539-6', 'http://loinc.org', 'XR Cervical spine 2 or 3 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000009', '44212-9', 'http://loinc.org', 'XR Cervical spine GE 4 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000010', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000011', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000012', '37908-1', 'http://loinc.org', 'XR Thoracic spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000013', '30773-6', 'http://loinc.org', 'XR Lumbar spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000014', '24970-6', 'http://loinc.org', 'XR Lumbar spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000015', '36735-9', 'http://loinc.org', 'XR Lumbar spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000016', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000017', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000018', '79371-1', 'http://loinc.org', 'XR Spine Lumbar and Sacrum GE 2 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000019', '36550-2', 'http://loinc.org', 'XR Abdomen Single view', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000020', '36641-9', 'http://loinc.org', 'XR Abdomen 2 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000021', '36293-9', 'http://loinc.org', 'XR Abdomen 3 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000022', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000023', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000024', '24640-5', 'http://loinc.org', 'XR Chest Apical lordotic', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000025', '24664-5', 'http://loinc.org', 'XR Clavicle Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000026', '30748-8', 'http://loinc.org', 'XR Shoulder Single view', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000027', '37840-6', 'http://loinc.org', 'XR Shoulder AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000028', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000029', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000030', '26146-1', 'http://loinc.org', 'XR Radius and Ulna Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000031', '37482-7', 'http://loinc.org', 'XR Wrist - bilateral 2 Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000032', '37710-1', 'http://loinc.org', 'XR Hand AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000033', '37684-8', 'http://loinc.org', 'XR Elbow AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000034', '37616-0', 'http://loinc.org', 'XR Pelvis Single view', '12921003', 'http://snomed.info/sct', 'Pelvic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000035', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000036', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000037', '37816-6', 'http://loinc.org', 'XR Tibia and Fibula AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000038', '37667-3', 'http://loinc.org', 'XR Ankle AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000039', '37701-0', 'http://loinc.org', 'XR Foot AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000040', '36709-4', 'http://loinc.org', 'XR Knee AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000041', '94682-2', 'http://loinc.org', 'XR Calcaneus GE 2 Views', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000042', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000043', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000044', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000045', '24558-9', 'http://loinc.org', 'US Abdomen', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000046', '24917-7', 'http://loinc.org', 'XR Skull Single view', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000047', '37867-9', 'http://loinc.org', 'XR Skull 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000048', '37858-8', 'http://loinc.org', 'XR Sinuses Lateral', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000049', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000050', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000051', '47983-2', 'http://loinc.org', 'XR Mastoid - bilateral 1 or 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000052', '24940-9', 'http://loinc.org', 'XR Cervical spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000053', '43539-6', 'http://loinc.org', 'XR Cervical spine 2 or 3 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000054', '44212-9', 'http://loinc.org', 'XR Cervical spine GE 4 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000055', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000056', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000057', '37908-1', 'http://loinc.org', 'XR Thoracic spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000058', '30773-6', 'http://loinc.org', 'XR Lumbar spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000059', '24970-6', 'http://loinc.org', 'XR Lumbar spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000060', '36735-9', 'http://loinc.org', 'XR Lumbar spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000061', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000062', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000063', '79371-1', 'http://loinc.org', 'XR Spine Lumbar and Sacrum GE 2 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000064', '36550-2', 'http://loinc.org', 'XR Abdomen Single view', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000065', '36641-9', 'http://loinc.org', 'XR Abdomen 2 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000066', '36293-9', 'http://loinc.org', 'XR Abdomen 3 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000067', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000068', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000069', '24640-5', 'http://loinc.org', 'XR Chest Apical lordotic', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000070', '24664-5', 'http://loinc.org', 'XR Clavicle Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000071', '30748-8', 'http://loinc.org', 'XR Shoulder Single view', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000072', '37840-6', 'http://loinc.org', 'XR Shoulder AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000073', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000074', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000075', '26146-1', 'http://loinc.org', 'XR Radius and Ulna Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000076', '37482-7', 'http://loinc.org', 'XR Wrist - bilateral 2 Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000077', '37710-1', 'http://loinc.org', 'XR Hand AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000078', '37684-8', 'http://loinc.org', 'XR Elbow AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000079', '37616-0', 'http://loinc.org', 'XR Pelvis Single view', '12921003', 'http://snomed.info/sct', 'Pelvic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000080', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000081', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000082', '37816-6', 'http://loinc.org', 'XR Tibia and Fibula AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000083', '37667-3', 'http://loinc.org', 'XR Ankle AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000084', '37701-0', 'http://loinc.org', 'XR Foot AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000085', '36709-4', 'http://loinc.org', 'XR Knee AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000086', '94682-2', 'http://loinc.org', 'XR Calcaneus GE 2 Views', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000087', '24558-9', 'http://loinc.org', 'US Abdomen', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('J000088', '83019-0', 'http://loinc.org', 'XR Chest and Abdomen and Pelvis View babygram', '416775004', 'http://snomed.info/sct', 'Chest and/or abdomen and/or pelvis structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251001', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251002', '24917-7', 'http://loinc.org', 'XR Skull Single view', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251003', '37867-9', 'http://loinc.org', 'XR Skull 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251004', '37858-8', 'http://loinc.org', 'XR Sinuses Lateral', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251005', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251006', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251007', '47983-2', 'http://loinc.org', 'XR Mastoid - bilateral 1 or 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251008', '24940-9', 'http://loinc.org', 'XR Cervical spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251009', '43539-6', 'http://loinc.org', 'XR Cervical spine 2 or 3 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251010', '44212-9', 'http://loinc.org', 'XR Cervical spine GE 4 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251011', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251012', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251013', '37908-1', 'http://loinc.org', 'XR Thoracic spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251014', '30773-6', 'http://loinc.org', 'XR Lumbar spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251015', '24970-6', 'http://loinc.org', 'XR Lumbar spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251016', '36735-9', 'http://loinc.org', 'XR Lumbar spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251017', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251018', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251019', '79371-1', 'http://loinc.org', 'XR Spine Lumbar and Sacrum GE 2 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251020', '36550-2', 'http://loinc.org', 'XR Abdomen Single view', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251021', '36641-9', 'http://loinc.org', 'XR Abdomen 2 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251022', '36293-9', 'http://loinc.org', 'XR Abdomen 3 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251023', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251024', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251025', '24640-5', 'http://loinc.org', 'XR Chest Apical lordotic', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251026', '24664-5', 'http://loinc.org', 'XR Clavicle Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251027', '30748-8', 'http://loinc.org', 'XR Shoulder Single view', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251028', '37840-6', 'http://loinc.org', 'XR Shoulder AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251029', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251030', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251031', '26146-1', 'http://loinc.org', 'XR Radius and Ulna Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251032', '37482-7', 'http://loinc.org', 'XR Wrist - bilateral 2 Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251033', '37710-1', 'http://loinc.org', 'XR Hand AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251034', '37684-8', 'http://loinc.org', 'XR Elbow AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251035', '37616-0', 'http://loinc.org', 'XR Pelvis Single view', '12921003', 'http://snomed.info/sct', 'Pelvic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251036', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251037', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251038', '37816-6', 'http://loinc.org', 'XR Tibia and Fibula AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251039', '37667-3', 'http://loinc.org', 'XR Ankle AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251040', '37701-0', 'http://loinc.org', 'XR Foot AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251041', '36709-4', 'http://loinc.org', 'XR Knee AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251042', '94682-2', 'http://loinc.org', 'XR Calcaneus GE 2 Views', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R251043', '24558-9', 'http://loinc.org', 'US Abdomen', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252001', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252002', '24917-7', 'http://loinc.org', 'XR Skull Single view', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252003', '37867-9', 'http://loinc.org', 'XR Skull 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252004', '37858-8', 'http://loinc.org', 'XR Sinuses Lateral', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252005', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252006', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252007', '47983-2', 'http://loinc.org', 'XR Mastoid - bilateral 1 or 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252008', '24940-9', 'http://loinc.org', 'XR Cervical spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252009', '43539-6', 'http://loinc.org', 'XR Cervical spine 2 or 3 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252010', '44212-9', 'http://loinc.org', 'XR Cervical spine GE 4 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252011', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252012', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252013', '37908-1', 'http://loinc.org', 'XR Thoracic spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252014', '30773-6', 'http://loinc.org', 'XR Lumbar spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252015', '24970-6', 'http://loinc.org', 'XR Lumbar spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252016', '36735-9', 'http://loinc.org', 'XR Lumbar spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252017', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252018', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252019', '79371-1', 'http://loinc.org', 'XR Spine Lumbar and Sacrum GE 2 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252020', '36550-2', 'http://loinc.org', 'XR Abdomen Single view', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252021', '36641-9', 'http://loinc.org', 'XR Abdomen 2 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252022', '36293-9', 'http://loinc.org', 'XR Abdomen 3 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252023', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252024', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252025', '24640-5', 'http://loinc.org', 'XR Chest Apical lordotic', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252026', '24664-5', 'http://loinc.org', 'XR Clavicle Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252027', '30748-8', 'http://loinc.org', 'XR Shoulder Single view', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252028', '37840-6', 'http://loinc.org', 'XR Shoulder AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252029', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252030', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252031', '26146-1', 'http://loinc.org', 'XR Radius and Ulna Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252032', '37482-7', 'http://loinc.org', 'XR Wrist - bilateral 2 Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252033', '37710-1', 'http://loinc.org', 'XR Hand AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252034', '37684-8', 'http://loinc.org', 'XR Elbow AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252035', '37616-0', 'http://loinc.org', 'XR Pelvis Single view', '12921003', 'http://snomed.info/sct', 'Pelvic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252036', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252037', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252038', '37816-6', 'http://loinc.org', 'XR Tibia and Fibula AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252039', '37667-3', 'http://loinc.org', 'XR Ankle AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252040', '37701-0', 'http://loinc.org', 'XR Foot AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252041', '36709-4', 'http://loinc.org', 'XR Knee AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252042', '94682-2', 'http://loinc.org', 'XR Calcaneus GE 2 Views', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R252043', '24558-9', 'http://loinc.org', 'US Abdomen', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253002', '24917-7', 'http://loinc.org', 'XR Skull Single view', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253003', '37867-9', 'http://loinc.org', 'XR Skull 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253004', '37858-8', 'http://loinc.org', 'XR Sinuses Lateral', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253005', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253006', '24834-4', 'http://loinc.org', 'XR Nasal bones Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253007', '47983-2', 'http://loinc.org', 'XR Mastoid - bilateral 1 or 2 Views', '272679001', 'http://snomed.info/sct', 'Bone structure of head (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253008', '24940-9', 'http://loinc.org', 'XR Cervical spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253009', '43539-6', 'http://loinc.org', 'XR Cervical spine 2 or 3 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253010', '44212-9', 'http://loinc.org', 'XR Cervical spine GE 4 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253011', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253012', '30753-8', 'http://loinc.org', 'XR Thoracic spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253013', '37908-1', 'http://loinc.org', 'XR Thoracic spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253014', '30773-6', 'http://loinc.org', 'XR Lumbar spine Single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253015', '24970-6', 'http://loinc.org', 'XR Lumbar spine AP and Lateral', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253016', '36735-9', 'http://loinc.org', 'XR Lumbar spine AP and Lateral and oblique', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253017', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253018', '44206-1', 'http://loinc.org', 'XR Thoracic and lumbar spine for scoliosis single view', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253019', '79371-1', 'http://loinc.org', 'XR Spine Lumbar and Sacrum GE 2 Views', '44300000', 'http://snomed.info/sct', 'Entire vertebral column (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253020', '36550-2', 'http://loinc.org', 'XR Abdomen Single view', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253021', '36641-9', 'http://loinc.org', 'XR Abdomen 2 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253022', '36293-9', 'http://loinc.org', 'XR Abdomen 3 Views', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253023', '36572-6', 'http://loinc.org', 'XR Chest AP', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253024', '36687-2', 'http://loinc.org', 'XR Chest AP and Lateral', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253025', '24640-5', 'http://loinc.org', 'XR Chest Apical lordotic', '51185008', 'http://snomed.info/sct', 'Thoracic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253026', '24664-5', 'http://loinc.org', 'XR Clavicle Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253027', '30748-8', 'http://loinc.org', 'XR Shoulder Single view', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253028', '37840-6', 'http://loinc.org', 'XR Shoulder AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253029', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253030', '37062-7', 'http://loinc.org', 'XR Humerus Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253031', '26146-1', 'http://loinc.org', 'XR Radius and Ulna Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253032', '37482-7', 'http://loinc.org', 'XR Wrist - bilateral 2 Views', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253033', '37710-1', 'http://loinc.org', 'XR Hand AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253034', '37684-8', 'http://loinc.org', 'XR Elbow AP and Lateral', '120574008', 'http://snomed.info/sct', 'Upper extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253035', '37616-0', 'http://loinc.org', 'XR Pelvis Single view', '12921003', 'http://snomed.info/sct', 'Pelvic structure (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253036', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253037', '37692-1', 'http://loinc.org', 'XR Femur AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253038', '37816-6', 'http://loinc.org', 'XR Tibia and Fibula AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253039', '37667-3', 'http://loinc.org', 'XR Ankle AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253040', '37701-0', 'http://loinc.org', 'XR Foot AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253041', '36709-4', 'http://loinc.org', 'XR Knee AP and Lateral', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253042', '94682-2', 'http://loinc.org', 'XR Calcaneus GE 2 Views', '120575009', 'http://snomed.info/sct', 'Lower extremity part (body structure)');
INSERT INTO `satu_sehat_mapping_radiologi` (`kd_jenis_prw`, `code`, `system`, `display`, `sampel_code`, `sampel_system`, `sampel_display`) VALUES ('R253043', '24558-9', 'http://loinc.org', 'US Abdomen', '113345001', 'http://snomed.info/sct', 'Abdominal structure (body structure)');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
